{{- $cfg := .Values.influxdb }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $cfg.name }}
  labels:
    {{- include "optscale.labels" (dict "root" . "name" $cfg.name) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $cfg.servicePort }}
      targetPort: http
      protocol: TCP
      name: {{ $cfg.name }}
  selector:
    {{- include "optscale.selectorLabels" (dict "root" . "name" $cfg.name) | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $cfg.name }}
  labels:
    {{- include "optscale.labels" (dict "root" . "name" $cfg.name) | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ $cfg.name }}
  selector:
    matchLabels:
      {{- include "optscale.selectorLabels" (dict "root" . "name" $cfg.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "optscale.selectorLabels" (dict "root" . "name" $cfg.name) | nindent 8 }}
    spec:
      {{- include "optscale.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: {{ $cfg.name }}
          image: {{ include "optscale.image" (dict "root" . "repo" $cfg.image "tag" $cfg.imageTag) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ $cfg.containerPort }}
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with $cfg.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb
      {{- if not $cfg.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
      {{- include "optscale.podScheduling" (dict "root" . "comp" $cfg) | nindent 6 }}
  {{- if $cfg.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- with ($cfg.persistence.storageClass | default .Values.global.storageClass) }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ $cfg.persistence.size }}
  {{- end }}
