{{- if not .Values.config.secrets.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secret
  labels:
    {{- include "optscale.labels" (dict "root" . "name" "cluster-secret") | nindent 4 }}
type: Opaque
data:
  cluster_secret: {{ .Values.config.secrets.cluster | b64enc | quote }}
{{- end }}
