{{- if not .Values.configurator.existingConfigSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: optscale-config
  labels:
    {{- include "optscale.labels" (dict "root" . "name" "configurator") | nindent 4 }}
type: Opaque
stringData:
  config: |
{{ include "optscale.configYaml" . | indent 4 }}
{{- end }}
