{{- if not .Values.config.existingSecretConfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: optscale-secret-config
  labels:
    {{- include "optscale.labels" (dict "root" . "name" "configurator") | nindent 4 }}
type: Opaque
stringData:
  etcd.yaml: |
    {{- include "optscale.secretConfigYaml" . | nindent 4 }}
{{- end }}
